apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    meta.helm.sh/release-name: nginx-app
    meta.helm.sh/release-namespace: accounts
  creationTimestamp: "2025-07-20T08:26:56Z"
  generation: 4
  labels:
    app: nginx
    app.kubernetes.io/managed-by: Helm
    release: nginx-app
  name: nginx-app-nginx
  namespace: accounts
  resourceVersion: "1753001045047119021"
  uid: e6b0f794-18c2-4afb-b5dc-835ddb5deb4e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
      release: nginx-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        release: nginx-app
    spec:
      containers:
      - image: nginx:1-alpine3.22-perl
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-20T08:33:26Z"
    lastUpdateTime: "2025-07-20T08:33:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-20T08:26:58Z"
    lastUpdateTime: "2025-07-20T08:44:05Z"
    message: ReplicaSet "nginx-app-nginx-7d77987bdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
